### ISSUE TITLE
photo2shape

### ISSUE THREAD

**Issue by ekolabynet** [alexbruy/photo2shape#13]
Hello, 
first of all, thanks for this plugin it is very useful in my work. 
Do you plan migration to QGIS 3.0? It is the only one plugin that force me to stay with 2.18 :-). 
Best Regards
Piotr Mędrzycki

**Comment by alexbruy** [comment]
@ekolabynet it was migrated more than month ago and available from my repository https://plugins.bruy.me/plugins/plugins.xml as well as other plugins.

**Comment by ekolabynet** [comment]
I've downloaded it and had exifread 2.1.2 installed, but it dowesn't load after installation:
Could you point me to the solution in my case?
Herewith I enclose qgis response:
*********************************
> Can't load plugin  'photo2shape' 

ModuleNotFoundError: No module named 'exifread' 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 311, in loadPlugin
    __import__(packageName)
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/head/.local/share/QGIS/QGIS3/profiles/default/python/plugins/photo2shape/__init__.py", line 28, in 
    from photo2shape.photo2shapeplugin import Photo2ShapePlugin
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/head/.local/share/QGIS/QGIS3/profiles/default/python/plugins/photo2shape/photo2shapeplugin.py", line 36, in 
    from photo2shape.gui.photo2shapedialog import Photo2ShapeDialog
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/head/.local/share/QGIS/QGIS3/profiles/default/python/plugins/photo2shape/gui/photo2shapedialog.py", line 37, in 
    from photo2shape.photoimporter import PhotoImporter
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/head/.local/share/QGIS/QGIS3/profiles/default/python/plugins/photo2shape/photoimporter.py", line 30, in 
    import exifread
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'exifread'


Wersja Pythona: 3.6.3 (default, Oct  3 2017, 21:45:48) [GCC 7.2.0] 
Wersja QGIS: 3.0.0-Girona Girona, 0def61c 

Lokalizacja Pythona:
/usr/share/qgis/python
/home/head/.local/share/QGIS/QGIS3/profiles/default/python
/home/head/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python36.zip
/usr/lib/python3.6
/usr/lib/python3.6/lib-dynload
/usr/local/lib/python3.6/dist-packages
/usr/lib/python3/dist-packages
/home/head/.local/share/QGIS/QGIS3/profiles/default/python
/home/head/.local/share/QGIS/QGIS3/profiles/default/python/plugins/mmqgis/forms
/home/head/.local/share/QGIS/QGIS3/profiles/default/python/plugins/shapetools/ext-libs

**Comment by alexbruy** [comment]
Just a guess, maybe you installed exifread for Python 2? Can you import exifread from Python 3?

**Comment by ekolabynet** [comment]
yeah, I've  installed pip3, exifread and have comments like this:

***********************
Nie można wczytać wtyczki 'photo2shape' 

AttributeError: type object 'QgsMessageLog' has no attribute 'INFO' 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 311, in loadPlugin
    __import__(packageName)
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/head/.local/share/QGIS/QGIS3/profiles/default/python/plugins/photo2shape/__init__.py", line 28, in 
    from photo2shape.photo2shapeplugin import Photo2ShapePlugin
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/head/.local/share/QGIS/QGIS3/profiles/default/python/plugins/photo2shape/photo2shapeplugin.py", line 36, in 
    from photo2shape.gui.photo2shapedialog import Photo2ShapeDialog
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/head/.local/share/QGIS/QGIS3/profiles/default/python/plugins/photo2shape/gui/photo2shapedialog.py", line 43, in 
    class Photo2ShapeDialog(BASE, WIDGET):
  File "/home/head/.local/share/QGIS/QGIS3/profiles/default/python/plugins/photo2shape/gui/photo2shapedialog.py", line 142, in Photo2ShapeDialog
    def logMessage(self, message, level=QgsMessageLog.INFO):
AttributeError: type object 'QgsMessageLog' has no attribute 'INFO'


Wersja Pythona: 3.6.3 (default, Oct  3 2017, 21:45:48) [GCC 7.2.0] 
Wersja QGIS: 3.0.0-Girona Girona, 0def61c 

Lokalizacja Pythona:
/usr/share/qgis/python
/home/head/.local/share/QGIS/QGIS3/profiles/default/python
/home/head/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python36.zip
/usr/lib/python3.6
/usr/lib/python3.6/lib-dynload
/usr/local/lib/python3.6/dist-packages
/usr/lib/python3/dist-packages
/home/head/.local/share/QGIS/QGIS3/profiles/default/python
/home/head/.local/share/QGIS/QGIS3/profiles/default/python/plugins/mmqgis/forms
/home/head/.local/share/QGIS/QGIS3/profiles/default/python/plugins/shapetools/ext-libs
/DATA/APPL/APPL_Skanska/Jasminowa/FTP/Monitoring/GIS/Projekty

**Comment by alexbruy** [comment]
Should be fixed in 2.1

**Comment by ekolabynet** [comment]
Many thanks :-).
