### ISSUE TITLE
AttributeError: type object 'QgsMessageLog' has no attribute 'INFO'

### ISSUE THREAD

**Issue by Minu16** [alexbruy/photo2shape#16]
Hi, 

I am using QGIS 3.4.5 and tried to install photo2shape, everytime when I tried it says "Couldn't load plugin", and the error message shows like this:

AttributeError: type object 'QgsMessageLog' has no attribute 'INFO' 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.4/apps/qgis-ltr/./python\qgis\utils.py", line 309, in loadPlugin
    __import__(packageName)
  File "C:/PROGRA~1/QGIS3~1.4/apps/qgis-ltr/./python\qgis\utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/QR5962/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\photo2shape\__init__.py", line 28, in 
    from photo2shape.photo2shapeplugin import Photo2ShapePlugin
  File "C:/PROGRA~1/QGIS3~1.4/apps/qgis-ltr/./python\qgis\utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/QR5962/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\photo2shape\photo2shapeplugin.py", line 36, in 
    from photo2shape.gui.photo2shapedialog import Photo2ShapeDialog
  File "C:/PROGRA~1/QGIS3~1.4/apps/qgis-ltr/./python\qgis\utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/QR5962/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\photo2shape\gui\photo2shapedialog.py", line 43, in 
    class Photo2ShapeDialog(BASE, WIDGET):
  File "C:/Users/QR5962/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\photo2shape\gui\photo2shapedialog.py", line 142, in Photo2ShapeDialog
    def logMessage(self, message, level=QgsMessageLog.INFO):
AttributeError: type object 'QgsMessageLog' has no attribute 'INFO'

Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.4.5-Madeira Madeira, 89ee6f6e23 

Python Path:
C:/Users/QR5962/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\WaterNetAnalyzer-master
C:/Users/QR5962/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\spatial_query_with_values
C:/PROGRA~1/QGIS3~1.4/apps/qgis-ltr/./python
C:/Users/QR5962/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/QR5962/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS3~1.4/apps/qgis-ltr/./python/plugins
C:\Program Files\QGIS 3.4\bin\python37.zip
C:\PROGRA~1\QGIS3~1.4\apps\Python37\DLLs
C:\PROGRA~1\QGIS3~1.4\apps\Python37\lib
C:\Program Files\QGIS 3.4\bin
C:\PROGRA~1\QGIS3~1.4\apps\Python37
C:\PROGRA~1\QGIS3~1.4\apps\Python37\lib\site-packages
C:\PROGRA~1\QGIS3~1.4\apps\Python37\lib\site-packages\win32
C:\PROGRA~1\QGIS3~1.4\apps\Python37\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3~1.4\apps\Python37\lib\site-packages\Pythonwin
C:/Users/QR5962/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\QR5962\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\postgisQueryBuilder
C:\Users\QR5962\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\postgisQueryBuilder\extlibs
C:/Users/QR5962/Downloads/GIS uses

I didn't install exifread since I have gdal installed, i dont know if it will affect the installation.
Btw thx for sharing the source code!

**Comment by alexbruy** [comment]
Looks like you have very old plugin version. This was fixed years ago. Please install latest plugin from the repository.

**Comment by Minu16** [comment]
Thank you, but i tried the latest version, and it shown like this:

Couldn't load plugin 'photo2shape-master' 

ModuleNotFoundError: No module named 'photo2shape.gui.photo2shapedialog' 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.4/apps/qgis-ltr/./python\qgis\utils.py", line 309, in loadPlugin
    __import__(packageName)
  File "C:/PROGRA~1/QGIS3~1.4/apps/qgis-ltr/./python\qgis\utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/QR5962/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\photo2shape-master\__init__.py", line 28, in 
    from photo2shape.photo2shapeplugin import Photo2ShapePlugin
  File "C:/PROGRA~1/QGIS3~1.4/apps/qgis-ltr/./python\qgis\utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/QR5962/Downloads/GIS uses\photo2shape\__init__.py", line 28, in 
    from photo2shape.photo2shapeplugin import Photo2ShapePlugin
  File "C:/PROGRA~1/QGIS3~1.4/apps/qgis-ltr/./python\qgis\utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/QR5962/Downloads/GIS uses\photo2shape\photo2shapeplugin.py", line 36, in 
    from photo2shape.gui.photo2shapedialog import Photo2ShapeDialog
  File "C:/PROGRA~1/QGIS3~1.4/apps/qgis-ltr/./python\qgis\utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'photo2shape.gui.photo2shapedialog'


Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.4.5-Madeira Madeira, 89ee6f6e23 

Python Path:
C:/Users/QR5962/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\WaterNetAnalyzer-master
C:/Users/QR5962/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\spatial_query_with_values
C:/PROGRA~1/QGIS3~1.4/apps/qgis-ltr/./python
C:/Users/QR5962/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/QR5962/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS3~1.4/apps/qgis-ltr/./python/plugins
C:\Program Files\QGIS 3.4\bin\python37.zip
C:\PROGRA~1\QGIS3~1.4\apps\Python37\DLLs
C:\PROGRA~1\QGIS3~1.4\apps\Python37\lib
C:\Program Files\QGIS 3.4\bin
C:\PROGRA~1\QGIS3~1.4\apps\Python37
C:\PROGRA~1\QGIS3~1.4\apps\Python37\lib\site-packages
C:\PROGRA~1\QGIS3~1.4\apps\Python37\lib\site-packages\win32
C:\PROGRA~1\QGIS3~1.4\apps\Python37\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3~1.4\apps\Python37\lib\site-packages\Pythonwin
C:/Users/QR5962/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\QR5962\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\postgisQueryBuilder
C:\Users\QR5962\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\postgisQueryBuilder\extlibs
C:/Users/QR5962/Downloads/GIS uses

**Comment by Minu16** [comment]
> Looks like you have very old plugin version. This was fixed years ago. Please install latest plugin from the repository.

Thank you, but i tried the latest version, and it shown like this:

Couldn't load plugin 'photo2shape-master'

ModuleNotFoundError: No module named 'photo2shape.gui.photo2shapedialog'
Traceback (most recent call last):
File "C:/PROGRA1/QGIS31.4/apps/qgis-ltr/./python\qgis\utils.py", line 309, in loadPlugin
import(packageName)
File "C:/PROGRA1/QGIS31.4/apps/qgis-ltr/./python\qgis\utils.py", line 672, in _import
mod = builtin_import(name, globals, locals, fromlist, level)
File "C:/Users/QR5962/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\photo2shape-master_init.py", line 28, in
from photo2shape.photo2shapeplugin import Photo2ShapePlugin
File "C:/PROGRA1/QGIS31.4/apps/qgis-ltr/./python\qgis\utils.py", line 672, in _import
mod = builtin_import(name, globals, locals, fromlist, level)
File "C:/Users/QR5962/Downloads/GIS uses\photo2shape_init.py", line 28, in
from photo2shape.photo2shapeplugin import Photo2ShapePlugin
File "C:/PROGRA1/QGIS31.4/apps/qgis-ltr/./python\qgis\utils.py", line 672, in _import
mod = _builtin_import(name, globals, locals, fromlist, level)
File "C:/Users/QR5962/Downloads/GIS uses\photo2shape\photo2shapeplugin.py", line 36, in
from photo2shape.gui.photo2shapedialog import Photo2ShapeDialog
File "C:/PROGRA1/QGIS31.4/apps/qgis-ltr/./python\qgis\utils.py", line 672, in _import
mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'photo2shape.gui.photo2shapedialog'

Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)]
QGIS version: 3.4.5-Madeira Madeira, 89ee6f6e23

Python Path:
C:/Users/QR5962/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\WaterNetAnalyzer-master
C:/Users/QR5962/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\spatial_query_with_values
C:/PROGRA1/QGIS31.4/apps/qgis-ltr/./python
C:/Users/QR5962/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/QR5962/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA1/QGIS31.4/apps/qgis-ltr/./python/plugins
C:\Program Files\QGIS 3.4\bin\python37.zip
C:\PROGRA1\QGIS31.4\apps\Python37\DLLs
C:\PROGRA1\QGIS31.4\apps\Python37\lib
C:\Program Files\QGIS 3.4\bin
C:\PROGRA1\QGIS31.4\apps\Python37
C:\PROGRA1\QGIS31.4\apps\Python37\lib\site-packages
C:\PROGRA1\QGIS31.4\apps\Python37\lib\site-packages\win32
C:\PROGRA1\QGIS31.4\apps\Python37\lib\site-packages\win32\lib
C:\PROGRA1\QGIS31.4\apps\Python37\lib\site-packages\Pythonwin
C:/Users/QR5962/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\QR5962\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\postgisQueryBuilder
C:\Users\QR5962\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\postgisQueryBuilder\extlibs
C:/Users/QR5962/Downloads/GIS uses

**Comment by alexbruy** [comment]
Please don't use files from GitHub if you don't know why you need it and how to use them, GitHub is for developers. There is a plugin repository with plugins for average users.
