### ISSUE TITLE
global name 'translationPath is not defined'

### ISSUE THREAD

**Issue by ponceta** [alexbruy/photo2shape#9]
I get an error when loading the photo2shape extension. I have installed exif read 2.1.2. using pip. (qgis osgeo4w installer used on windows 7 x64)

```
Impossible de charger l'extension photo2shape provoque une erreur lors de l'appel de sa méthode classFactory() 

NameError: global name 'translationPath' is not defined 
Traceback (most recent call last):
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 333, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/pulpoar/.qgis2/python/plugins\photo2shape\__init__.py", line 31, in classFactory
    return Photo2ShapePlugin(iface)
  File "C:/Users/pulpoar/.qgis2/python/plugins\photo2shape\photo2shape_plugin.py", line 59, in __init__
    self.translator.load(translationPath)
NameError: global name 'translationPath' is not defined


Version de Python : 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] 
Version de QGIS : 2.18.9 Las Palmas, 3a16a4e 
```

**Comment by ponceta** [comment]
Corrected on master.
